### ISSUE TITLE
mergerfs.ctl info returns "No data available"

### ISSUE THREAD

**Issue by willemw12** [trapexit/mergerfs-tools#53] opened 2017-12-02 08:21 UTC
mergerfs.ctl info returns an error:

    $ mergerfs.ctl info
    Traceback (most recent call last):
      File "/usr/bin/mergerfs.ctl", line 272, in <module>
        main()
      File "/usr/bin/mergerfs.ctl", line 264, in main
        args.func(fspaths,args)
      File "/usr/bin/mergerfs.ctl", line 243, in cmd_info
        print_mergerfs_info(fspaths)
      File "/usr/bin/mergerfs.ctl", line 97, in print_mergerfs_info
        version   = os.getxattr(ctrlfile,'user.mergerfs.version')
    OSError: [Errno 61] No data available: '/mnt/pool/.mergerfs'

And:

    $ xattr -l /mnt/pool/.mergerfs
    ...
    user.mergerfs.policies: all,epall,epff,eplfs,eplus,epmfs,eprand,erofs,ff,lfs,lus,mfs,newest,rand
    No such xattr: user.mergerfs.version
    user.mergerfs.pid: 292
    ...

Using the latest mergerfs-tools and Python 3.6.3.

**Comment by trapexit** [comment] 2017-12-02 08:23
Did you compile mergerfs yourself?

**Comment by willemw12** [comment] 2017-12-02 08:40
Yes, on archlinuxarm armv7h from package https://aur.archlinux.org/packages/mergerfs/

**Comment by trapexit** [comment] 2017-12-02 14:03
They are using the wrong source package. It should be https://github.com/trapexit/mergerfs/releases/download/2.23.1/mergerfs-2.23.1.tar.gz

**Comment by trapexit** [comment] 2017-12-02 15:03
The issue is that the version value hasn't been set within the code... which compiling with git or with the release tar.gz would have properly set. I'll try to have it default to "unknown" or something so that doesn't happen.

**Comment by willemw12** [comment] 2017-12-02 15:24
Thanks. Checked `mergerfs.ctl info` again with mergerfs built with that URL you mentioned and the mergerfs version is now available.

I have left a comment in the AUR about this issue.

**Comment by pheerai** [comment] 2017-12-02 18:21
@willemw12 This should be fixed in the `PKGBUILD` now, could you retry and let me know if it worked?

Thanks a lot.

**Closed** 2017-12-02 18:44 UTC

**Comment by willemw12** [comment] 2017-12-03 10:41
@pheerai: Fixed in `PKGBUILD`.
